In [1]:
import pandas as pd

df = pd.read_csv('C:/Users/julio/Downloads/archive (24)/spambase_csv.csv')

In [2]:
df.describe()

,word_freq_make,word_freq_address,word_freq_all,word_freq_3d,word_freq_our,word_freq_over,word_freq_remove,word_freq_internet,word_freq_order,word_freq_mail,...,char_freq_%3B,char_freq_%28,char_freq_%5B,char_freq_%21,char_freq_%24,char_freq_%23,capital_run_length_average,capital_run_length_longest,capital_run_length_total,class
count,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,...,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000
mean,0.104553,0.213015,0.280656,0.065425,0.312223,0.095901,0.114208,0.105295,0.090067,0.239413,...,0.038575,0.139030,0.016976,0.269071,0.075811,0.044238,5.191515,52.172789,283.289285,0.394045
std,0.305358,1.290575,0.504143,1.395151,0.672513,0.273824,0.391441,0.401071,0.278616,0.644755,...,0.243471,0.270355,0.109394,0.815672,0.245882,0.429342,31.729449,194.891310,606.347851,0.488698
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.588000,6.000000,35.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.065000,0.000000,0.000000,0.000000,0.000000,2.276000,15.000000,95.000000,0.000000
75%,0.000000,0.000000,0.420000,0.000000,0.380000,0.000000,0.000000,0.000000,0.000000,0.160000,...,0.000000,0.188000,0.000000,0.315000,0.052000,0.000000,3.706000,43.000000,266.000000,1.000000
max,4.540000,14.280000,5.100000,42.810000,10.000000,5.880000,7.270000,11.110000,5.260000,18.180000,...,4.385000,9.752000,4.081000,32.478000,6.003000,19.829000,1102.500000,9989.000000,15841.000000,1.000000

In [4]:
df.head(10)

,word_freq_make,word_freq_address,word_freq_all,word_freq_3d,word_freq_our,word_freq_over,word_freq_remove,word_freq_internet,word_freq_order,word_freq_mail,...,char_freq_%3B,char_freq_%28,char_freq_%5B,char_freq_%21,char_freq_%24,char_freq_%23,capital_run_length_average,capital_run_length_longest,capital_run_length_total,class
0,0.00,0.64,0.64,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.00,0.000,0.0,0.778,0.000,0.000,3.756,61,278,1
1,0.21,0.28,0.50,0.0,0.14,0.28,0.21,0.07,0.00,0.94,...,0.00,0.132,0.0,0.372,0.180,0.048,5.114,101,1028,1
2,0.06,0.00,0.71,0.0,1.23,0.19,0.19,0.12,0.64,0.25,...,0.01,0.143,0.0,0.276,0.184,0.010,9.821,485,2259,1
3,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.137,0.0,0.137,0.000,0.000,3.537,40,191,1
4,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.135,0.0,0.135,0.000,0.000,3.537,40,191,1
5,0.00,0.00,0.00,0.0,1.85,0.00,0.00,1.85,0.00,0.00,...,0.00,0.223,0.0,0.000,0.000,0.000,3.000,15,54,1
6,0.00,0.00,0.00,0.0,1.92,0.00,0.00,0.00,0.00,0.64,...,0.00,0.054,0.0,0.164,0.054,0.000,1.671,4,112,1
7,0.00,0.00,0.00,0.0,1.88,0.00,0.00,1.88,0.00,0.00,...,0.00,0.206,0.0,0.000,0.000,0.000,2.450,11,49,1
8,0.15,0.00,0.46,0.0,0.61,0.00,0.30,0.00,0.92,0.76,...,0.00,0.271,0.0,0.181,0.203,0.022,9.744,445,1257,1
9,0.06,0.12,0.77,0.0,0.19,0.32,0.38,0.00,0.06,0.00,...,0.04,0.030,0.0,0.244,0.081,0.000,1.729,43,749,1

In [5]:
df.isna().sum()

word_freq_make                0
word_freq_address             0
word_freq_all                 0
word_freq_3d                  0
word_freq_our                 0
word_freq_over                0
word_freq_remove              0
word_freq_internet            0
word_freq_order               0
word_freq_mail                0
word_freq_receive             0
word_freq_will                0
word_freq_people              0
word_freq_report              0
word_freq_addresses           0
word_freq_free                0
word_freq_business            0
word_freq_email               0
word_freq_you                 0
word_freq_credit              0
word_freq_your                0
word_freq_font                0
word_freq_000                 0
word_freq_money               0
word_freq_hp                  0
word_freq_hpl                 0
word_freq_george              0
word_freq_650                 0
word_freq_lab                 0
word_freq_labs                0
word_freq_telnet              0
word_freq_857                 0
word_freq_data                0
word_freq_415                 0
word_freq_85                  0
word_freq_technology          0
word_freq_1999                0
word_freq_parts               0
word_freq_pm                  0
word_freq_direct              0
word_freq_cs                  0
word_freq_meeting             0
word_freq_original            0
word_freq_project             0
word_freq_re                  0
word_freq_edu                 0
word_freq_table               0
word_freq_conference          0
char_freq_%3B                 0
char_freq_%28                 0
char_freq_%5B                 0
char_freq_%21                 0
char_freq_%24                 0
char_freq_%23                 0
capital_run_length_average    0
capital_run_length_longest    0
capital_run_length_total      0
class                         0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(391)

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df = df.apply(pd.to_numeric, errors='coerce')

In [12]:
X = df.drop("class", axis=1)
y = df["class"]

In [13]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [14]:
df = df.rename(columns={
    "word_freq_make": "freq_make",
    "word_freq_address": "freq_address",
    "word_freq_all": "freq_all",
    "char_freq_%3B": "freq_semicolon",
    "char_freq_%28": "freq_left_paren",
    "char_freq_%5B": "freq_left_bracket",
    "capital_run_length_average": "cap_avg",
    "capital_run_length_longest": "cap_longest",
    "capital_run_length_total": "cap_total",
    "class": "is_spam"
})

In [17]:
df.columns

Index(['freq_make', 'freq_address', 'freq_all', 'word_freq_3d',
       'word_freq_our', 'word_freq_over', 'word_freq_remove',
       'word_freq_internet', 'word_freq_order', 'word_freq_mail',
       'word_freq_receive', 'word_freq_will', 'word_freq_people',
       'word_freq_report', 'word_freq_addresses', 'word_freq_free',
       'word_freq_business', 'word_freq_email', 'word_freq_you',
       'word_freq_credit', 'word_freq_your', 'word_freq_font', 'word_freq_000',
       'word_freq_money', 'word_freq_hp', 'word_freq_hpl', 'word_freq_george',
       'word_freq_650', 'word_freq_lab', 'word_freq_labs', 'word_freq_telnet',
       'word_freq_857', 'word_freq_data', 'word_freq_415', 'word_freq_85',
       'word_freq_technology', 'word_freq_1999', 'word_freq_parts',
       'word_freq_pm', 'word_freq_direct', 'word_freq_cs', 'word_freq_meeting',
       'word_freq_original', 'word_freq_project', 'word_freq_re',
       'word_freq_edu', 'word_freq_table', 'word_freq_conference',
       'freq_semicolon', 'freq_left_paren', 'freq_left_bracket',
       'char_freq_%21', 'char_freq_%24', 'char_freq_%23', 'cap_avg',
       'cap_longest', 'cap_total', 'is_spam'],
      dtype='str')

In [18]:
df = df.rename(columns={
    'word_freq_3d': 'freq_3d',
    'word_freq_our': 'freq_our',
    'word_freq_over': 'freq_over',
    'word_freq_remove': 'freq_remove',
    'word_freq_internet': 'freq_internet',
    'word_freq_order': 'freq_order',
    'word_freq_mail': 'freq_mail',
    'word_freq_receive': 'freq_receive',
    'word_freq_will': 'freq_will',
    'word_freq_people': 'freq_people',
    'word_freq_report': 'freq_report',
    'word_freq_addresses': 'freq_addresses',
    'word_freq_free': 'freq_free',
    'word_freq_business': 'freq_business',
    'word_freq_email': 'freq_email',
    'word_freq_you': 'freq_you',
    'word_freq_credit': 'freq_credit',
    'word_freq_your': 'freq_your',
    'word_freq_font': 'freq_font',
    'word_freq_000': 'freq_000',
    'word_freq_money': 'freq_money',
    'word_freq_hp': 'freq_hp',
    'word_freq_hpl': 'freq_hpl',
    'word_freq_george': 'freq_george',
    'word_freq_650': 'freq_650',
    'word_freq_lab': 'freq_lab',
    'word_freq_labs': 'freq_labs',
    'word_freq_telnet': 'freq_telnet',
    'word_freq_857': 'freq_857',
    'word_freq_data': 'freq_data',
    'word_freq_415': 'freq_415',
    'word_freq_85': 'freq_85',
    'word_freq_technology': 'freq_technology',
    'word_freq_1999': 'freq_1999',
    'word_freq_parts': 'freq_parts',
    'word_freq_pm': 'freq_pm',
    'word_freq_direct': 'freq_direct',
    'word_freq_cs': 'freq_cs',
    'word_freq_meeting': 'freq_meeting',
    'word_freq_original': 'freq_original',
    'word_freq_project': 'freq_project',
    'word_freq_re': 'freq_re',
    'word_freq_edu': 'freq_edu',
    'word_freq_table': 'freq_table',
    'word_freq_conference': 'freq_conference',

    # character frequencies
    'freq_semicolon': 'char_semicolon',
    'freq_left_paren': 'char_left_paren',
    'freq_left_bracket': 'char_left_bracket',
    'char_freq_%21': 'char_exclamation',
    'char_freq_%24': 'char_dollar',
    'char_freq_%23': 'char_hash',

    # capital run lengths
    'cap_avg': 'cap_avg',
    'cap_longest': 'cap_longest',
    'cap_total': 'cap_total'
})

In [19]:
df.columns

Index(['freq_make', 'freq_address', 'freq_all', 'freq_3d', 'freq_our',
       'freq_over', 'freq_remove', 'freq_internet', 'freq_order', 'freq_mail',
       'freq_receive', 'freq_will', 'freq_people', 'freq_report',
       'freq_addresses', 'freq_free', 'freq_business', 'freq_email',
       'freq_you', 'freq_credit', 'freq_your', 'freq_font', 'freq_000',
       'freq_money', 'freq_hp', 'freq_hpl', 'freq_george', 'freq_650',
       'freq_lab', 'freq_labs', 'freq_telnet', 'freq_857', 'freq_data',
       'freq_415', 'freq_85', 'freq_technology', 'freq_1999', 'freq_parts',
       'freq_pm', 'freq_direct', 'freq_cs', 'freq_meeting', 'freq_original',
       'freq_project', 'freq_re', 'freq_edu', 'freq_table', 'freq_conference',
       'char_semicolon', 'char_left_paren', 'char_left_bracket',
       'char_exclamation', 'char_dollar', 'char_hash', 'cap_avg',
       'cap_longest', 'cap_total', 'is_spam'],
      dtype='str')

In [26]:
from sklearn.model_selection import train_test_split

X = df.drop("is_spam", axis=1)
y = df["is_spam"]

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.25, random_state=42)

print("Training size:", X_train.shape)
print("Test size:", X_test.shape)

Training size: (3157, 57)
Test size: (1053, 57)

In [28]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [29]:
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

log_model = LogisticRegression(max_iter=1000)

log_model.fit(X_train_scaled, y_train)

y_pred = log_model.predict(X_test_scaled)

accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)

print("\nAccuracy:", accuracy)
print("\nConfusion Matrix:", conf_matrix)
print("\nClasssification Report:", report)

Accuracy: 0.912630579297246

Confusion Matrix: [[585  29]
 [ 63 376]]

Classsification Report:               precision    recall  f1-score   support

           0       0.90      0.95      0.93       614
           1       0.93      0.86      0.89       439

    accuracy                           0.91      1053
   macro avg       0.92      0.90      0.91      1053
weighted avg       0.91      0.91      0.91      1053

In [30]:
pip install joblib

Requirement already satisfied: joblib in .\anaconda3\Lib\site-packages (1.5.3)
Note: you may need to restart the kernel to use updated packages.

In [32]:
import joblib

joblib.dump(log_model, "logistic_spam_model.pkl")

print("Model Saved")

Model Saved

In [33]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [34]:
rf_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=None, 
    random_state=42
)

In [35]:
rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

In [36]:
rf_accuracy = accuracy_score(y_test, rf_pred)
rf_conf_matrix = confusion_matrix(y_test, rf_pred)
rf_report = classification_report(y_test, rf_pred)

print("\nRandom Forest Accuracy:", rf_accuracy)
print("\nConfusion Matrix:", rf_conf_matrix)
print("\nClassification Report:", rf_report)

Random Forest Accuracy: 0.9458689458689459

Confusion Matrix: [[594  20]
 [ 37 402]]

Classification Report:               precision    recall  f1-score   support

           0       0.94      0.97      0.95       614
           1       0.95      0.92      0.93       439

    accuracy                           0.95      1053
   macro avg       0.95      0.94      0.94      1053
weighted avg       0.95      0.95      0.95      1053

In [37]:
joblib.dump(rf_model, "random_forest_spam_model.pkl")

['random_forest_spam_model.pkl']